// https://projecteuler.net/problem=2
//
//
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//
//   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
//  By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
//


let Fibonacci = 
    let generator (a:bigint,b:bigint) = 
        Some(a + b, (b, a+b) )
    Seq.unfold generator (0I,1I)

//test: Fibonacci |> Seq.take 10 |> Seq.iter (fun l -> printf "%A, " l)

let isEven (i:bigint) = i % 2I = 0I
let doesntExceedMax (i:bigint) = i < 400I

Fibonacci
    |> Seq.filter isEven
    |> Seq.where doesntExceedMax
    |> Seq.sum